### ISSUE TITLE
cakephp 3

### ISSUE THREAD

**Issue by datnguyenthang** [burzum/cakephp-cart-plugin#27]
Could you implement this plugin for cakephp 3?

**Comment by burzum** [comment]
I have a somewhat working version for Cake3 but it's not going to be open source, I want to sell it. Simply because people *will* earn money when running a shop and I find my photography hobby more rewarding than doing open source. People usually just take but don't give anything back, sorry. :) If you're interested in *buying* it let me know.

**Comment by tm070193** [comment]
Hello I'm interested in buying the plugin for Cake3. But I want to know the conditions (features, requirements, etc.)

**Comment by burzum** [comment]
It will require CakePHP 3.5, started to update the code to it. Features are the same as the v2 version.

How quickly do you need it? I'll pick my work up on this project if there is an interest in using it.
